(cl:defpackage novatel_msgs-msg
  (:use )
  (:export
   "<BESTVEL2>"
   "BESTVEL2"
   "<INSPVA>"
   "INSPVA"
   "<CORRIMUDATA>"
   "CORRIMUDATA"
   "<COMMONHEADER>"
   "COMMONHEADER"
   "<ACK>"
   "ACK"
   "<RAWIMU>"
   "RAWIMU"
   "<IMAGETIMESTAMP>"
   "IMAGETIMESTAMP"
   "<COMMONFOOTER>"
   "COMMONFOOTER"
   "<INSCOV>"
   "INSCOV"
   "<BESTPOS>"
   "BESTPOS"
   "<LOGFILESTATUS>"
   "LOGFILESTATUS"
   "<BESTXYZ>"
   "BESTXYZ"
   "<INSPVAX>"
   "INSPVAX"
   "<MARK1PVA>"
   "MARK1PVA"
  ))

