(cl:in-package status_pb_msgs-msg)
(cl:export '(DRIVING_MODE-VAL
          DRIVING_MODE
          ERROR_CODE-VAL
          ERROR_CODE
          ENGINE_STARTED-VAL
          ENGINE_STARTED
          ENGINE_RPM-VAL
          ENGINE_RPM
          SPEED_MPS-VAL
          SPEED_MPS
          ODOMETER_M-VAL
          ODOMETER_M
          FUEL_RANGE_M-VAL
          FUEL_RANGE_M
          THROTTLE_PERCENTAGE-VAL
          THROTTLE_PERCENTAGE
          BRAKE_PERCENTAGE-VAL
          BRAKE_PERCENTAGE
          GEAR_LOCATION-VAL
          GEAR_LOCATION
          STEERING_PERCENTAGE-VAL
          STEERING_PERCENTAGE
          STEERING_TORQUE_NM-VAL
          STEERING_TORQUE_NM
          PARKING_BRAKE-VAL
          PARKING_BRAKE
          HIGH_BEAM_SIGNAL-VAL
          HIGH_BEAM_SIGNAL
          LOW_BEAM_SIGNAL-VAL
          LOW_BEAM_SIGNAL
          LEFT_TURN_SIGNAL-VAL
          LEFT_TURN_SIGNAL
          RIGHT_TURN_SIGNAL-VAL
          RIGHT_TURN_SIGNAL
          HORN-VAL
          HORN
          WIPER-VAL
          WIPER
))