# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from status_pb_msgs/Status.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import header_pb_msgs.msg
import common_pb_msgs.msg
import status_pb_msgs.msg
import localization_pb_msgs.msg

class Status(genpy.Message):
  _md5sum = "c108e7cdb5158d560070b2d84145e09b"
  _type = "status_pb_msgs/Status"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """header_pb_msgs/Header header 
Chassis chassis 
localization_pb_msgs/Pose pose 

================================================================================
MSG: header_pb_msgs/Header
float64 timestamp_sec 
string module_name 
uint32 sequence_num 

================================================================================
MSG: status_pb_msgs/Chassis
int32 driving_mode 
int32 error_code 
bool engine_started 
float32 engine_rpm 
float32 speed_mps 
float32 odometer_m 
int32 fuel_range_m 
float32 throttle_percentage 
float32 brake_percentage 
int32 gear_location 
float32 steering_percentage 
float32 steering_torque_nm 
bool parking_brake 
bool high_beam_signal 
bool low_beam_signal 
bool left_turn_signal 
bool right_turn_signal 
bool horn 
bool wiper 

================================================================================
MSG: localization_pb_msgs/Pose
common_pb_msgs/PointENU position 
common_pb_msgs/Quaternion orientation 
common_pb_msgs/Point3D linear_velocity 
common_pb_msgs/Point3D linear_acceleration 
common_pb_msgs/Point3D angular_velocity 

================================================================================
MSG: common_pb_msgs/PointENU
float64 x 
float64 y 
float64 z 

================================================================================
MSG: common_pb_msgs/Quaternion
float64 qx 
float64 qy 
float64 qz 
float64 qw 

================================================================================
MSG: common_pb_msgs/Point3D
float64 x 
float64 y 
float64 z 
"""
  __slots__ = ['header','chassis','pose']
  _slot_types = ['header_pb_msgs/Header','status_pb_msgs/Chassis','localization_pb_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,chassis,pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Status, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = header_pb_msgs.msg.Header()
      if self.chassis is None:
        self.chassis = status_pb_msgs.msg.Chassis()
      if self.pose is None:
        self.pose = localization_pb_msgs.msg.Pose()
    else:
      self.header = header_pb_msgs.msg.Header()
      self.chassis = status_pb_msgs.msg.Chassis()
      self.pose = localization_pb_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_d.pack(self.header.timestamp_sec))
      _x = self.header.module_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_I2iB3fi2fi2f7B16d.pack(_x.header.sequence_num, _x.chassis.driving_mode, _x.chassis.error_code, _x.chassis.engine_started, _x.chassis.engine_rpm, _x.chassis.speed_mps, _x.chassis.odometer_m, _x.chassis.fuel_range_m, _x.chassis.throttle_percentage, _x.chassis.brake_percentage, _x.chassis.gear_location, _x.chassis.steering_percentage, _x.chassis.steering_torque_nm, _x.chassis.parking_brake, _x.chassis.high_beam_signal, _x.chassis.low_beam_signal, _x.chassis.left_turn_signal, _x.chassis.right_turn_signal, _x.chassis.horn, _x.chassis.wiper, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.qx, _x.pose.orientation.qy, _x.pose.orientation.qz, _x.pose.orientation.qw, _x.pose.linear_velocity.x, _x.pose.linear_velocity.y, _x.pose.linear_velocity.z, _x.pose.linear_acceleration.x, _x.pose.linear_acceleration.y, _x.pose.linear_acceleration.z, _x.pose.angular_velocity.x, _x.pose.angular_velocity.y, _x.pose.angular_velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = header_pb_msgs.msg.Header()
      if self.chassis is None:
        self.chassis = status_pb_msgs.msg.Chassis()
      if self.pose is None:
        self.pose = localization_pb_msgs.msg.Pose()
      end = 0
      start = end
      end += 8
      (self.header.timestamp_sec,) = _struct_d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.module_name = str[start:end].decode('utf-8')
      else:
        self.header.module_name = str[start:end]
      _x = self
      start = end
      end += 184
      (_x.header.sequence_num, _x.chassis.driving_mode, _x.chassis.error_code, _x.chassis.engine_started, _x.chassis.engine_rpm, _x.chassis.speed_mps, _x.chassis.odometer_m, _x.chassis.fuel_range_m, _x.chassis.throttle_percentage, _x.chassis.brake_percentage, _x.chassis.gear_location, _x.chassis.steering_percentage, _x.chassis.steering_torque_nm, _x.chassis.parking_brake, _x.chassis.high_beam_signal, _x.chassis.low_beam_signal, _x.chassis.left_turn_signal, _x.chassis.right_turn_signal, _x.chassis.horn, _x.chassis.wiper, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.qx, _x.pose.orientation.qy, _x.pose.orientation.qz, _x.pose.orientation.qw, _x.pose.linear_velocity.x, _x.pose.linear_velocity.y, _x.pose.linear_velocity.z, _x.pose.linear_acceleration.x, _x.pose.linear_acceleration.y, _x.pose.linear_acceleration.z, _x.pose.angular_velocity.x, _x.pose.angular_velocity.y, _x.pose.angular_velocity.z,) = _struct_I2iB3fi2fi2f7B16d.unpack(str[start:end])
      self.chassis.engine_started = bool(self.chassis.engine_started)
      self.chassis.parking_brake = bool(self.chassis.parking_brake)
      self.chassis.high_beam_signal = bool(self.chassis.high_beam_signal)
      self.chassis.low_beam_signal = bool(self.chassis.low_beam_signal)
      self.chassis.left_turn_signal = bool(self.chassis.left_turn_signal)
      self.chassis.right_turn_signal = bool(self.chassis.right_turn_signal)
      self.chassis.horn = bool(self.chassis.horn)
      self.chassis.wiper = bool(self.chassis.wiper)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_d.pack(self.header.timestamp_sec))
      _x = self.header.module_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_I2iB3fi2fi2f7B16d.pack(_x.header.sequence_num, _x.chassis.driving_mode, _x.chassis.error_code, _x.chassis.engine_started, _x.chassis.engine_rpm, _x.chassis.speed_mps, _x.chassis.odometer_m, _x.chassis.fuel_range_m, _x.chassis.throttle_percentage, _x.chassis.brake_percentage, _x.chassis.gear_location, _x.chassis.steering_percentage, _x.chassis.steering_torque_nm, _x.chassis.parking_brake, _x.chassis.high_beam_signal, _x.chassis.low_beam_signal, _x.chassis.left_turn_signal, _x.chassis.right_turn_signal, _x.chassis.horn, _x.chassis.wiper, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.qx, _x.pose.orientation.qy, _x.pose.orientation.qz, _x.pose.orientation.qw, _x.pose.linear_velocity.x, _x.pose.linear_velocity.y, _x.pose.linear_velocity.z, _x.pose.linear_acceleration.x, _x.pose.linear_acceleration.y, _x.pose.linear_acceleration.z, _x.pose.angular_velocity.x, _x.pose.angular_velocity.y, _x.pose.angular_velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = header_pb_msgs.msg.Header()
      if self.chassis is None:
        self.chassis = status_pb_msgs.msg.Chassis()
      if self.pose is None:
        self.pose = localization_pb_msgs.msg.Pose()
      end = 0
      start = end
      end += 8
      (self.header.timestamp_sec,) = _struct_d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.module_name = str[start:end].decode('utf-8')
      else:
        self.header.module_name = str[start:end]
      _x = self
      start = end
      end += 184
      (_x.header.sequence_num, _x.chassis.driving_mode, _x.chassis.error_code, _x.chassis.engine_started, _x.chassis.engine_rpm, _x.chassis.speed_mps, _x.chassis.odometer_m, _x.chassis.fuel_range_m, _x.chassis.throttle_percentage, _x.chassis.brake_percentage, _x.chassis.gear_location, _x.chassis.steering_percentage, _x.chassis.steering_torque_nm, _x.chassis.parking_brake, _x.chassis.high_beam_signal, _x.chassis.low_beam_signal, _x.chassis.left_turn_signal, _x.chassis.right_turn_signal, _x.chassis.horn, _x.chassis.wiper, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.qx, _x.pose.orientation.qy, _x.pose.orientation.qz, _x.pose.orientation.qw, _x.pose.linear_velocity.x, _x.pose.linear_velocity.y, _x.pose.linear_velocity.z, _x.pose.linear_acceleration.x, _x.pose.linear_acceleration.y, _x.pose.linear_acceleration.z, _x.pose.angular_velocity.x, _x.pose.angular_velocity.y, _x.pose.angular_velocity.z,) = _struct_I2iB3fi2fi2f7B16d.unpack(str[start:end])
      self.chassis.engine_started = bool(self.chassis.engine_started)
      self.chassis.parking_brake = bool(self.chassis.parking_brake)
      self.chassis.high_beam_signal = bool(self.chassis.high_beam_signal)
      self.chassis.low_beam_signal = bool(self.chassis.low_beam_signal)
      self.chassis.left_turn_signal = bool(self.chassis.left_turn_signal)
      self.chassis.right_turn_signal = bool(self.chassis.right_turn_signal)
      self.chassis.horn = bool(self.chassis.horn)
      self.chassis.wiper = bool(self.chassis.wiper)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_I2iB3fi2fi2f7B16d = struct.Struct("<I2iB3fi2fi2f7B16d")
_struct_d = struct.Struct("<d")
