// Generated by gencpp from file decision_pb_msgs/ObjectNudge.msg
// DO NOT EDIT!


#ifndef DECISION_PB_MSGS_MESSAGE_OBJECTNUDGE_H
#define DECISION_PB_MSGS_MESSAGE_OBJECTNUDGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <decision_pb_msgs/Range.h>

namespace decision_pb_msgs
{
template <class ContainerAllocator>
struct ObjectNudge_
{
  typedef ObjectNudge_<ContainerAllocator> Type;

  ObjectNudge_()
    : distance_l(0.0)
    , type(0)
    , preferred_distance_l()  {
    }
  ObjectNudge_(const ContainerAllocator& _alloc)
    : distance_l(0.0)
    , type(0)
    , preferred_distance_l(_alloc)  {
  (void)_alloc;
    }



   typedef double _distance_l_type;
  _distance_l_type distance_l;

   typedef int32_t _type_type;
  _type_type type;

   typedef  ::decision_pb_msgs::Range_<ContainerAllocator>  _preferred_distance_l_type;
  _preferred_distance_l_type preferred_distance_l;




  typedef boost::shared_ptr< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectNudge_

typedef ::decision_pb_msgs::ObjectNudge_<std::allocator<void> > ObjectNudge;

typedef boost::shared_ptr< ::decision_pb_msgs::ObjectNudge > ObjectNudgePtr;
typedef boost::shared_ptr< ::decision_pb_msgs::ObjectNudge const> ObjectNudgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision_pb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'perception_pb_msgs': ['/home/caros/ros/share/perception_pb_msgs/cmake/../msg'], 'prediction_pb_msgs': ['/home/caros/ros/share/prediction_pb_msgs/cmake/../msg'], 'decision_pb_msgs': ['/home/scmbuild/workspaces_cluster.tmp/tmp.20161206.225249.22574/baidu/adu/ros/pb_msgs/decision_pb_msgs/msg'], 'common_pb_msgs': ['/home/caros/ros/share/common_pb_msgs/cmake/../msg'], 'header_pb_msgs': ['/home/caros/ros/share/header_pb_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb0d3d4ff3a41e9fa643afca4c5c267e";
  }

  static const char* value(const ::decision_pb_msgs::ObjectNudge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb0d3d4ff3a41e9fULL;
  static const uint64_t static_value2 = 0xa643afca4c5c267eULL;
};

template<class ContainerAllocator>
struct DataType< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision_pb_msgs/ObjectNudge";
  }

  static const char* value(const ::decision_pb_msgs::ObjectNudge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance_l \n\
int32 type \n\
Range preferred_distance_l \n\
\n\
================================================================================\n\
MSG: decision_pb_msgs/Range\n\
float64 start \n\
float64 end \n\
";
  }

  static const char* value(const ::decision_pb_msgs::ObjectNudge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_l);
      stream.next(m.type);
      stream.next(m.preferred_distance_l);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ObjectNudge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision_pb_msgs::ObjectNudge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision_pb_msgs::ObjectNudge_<ContainerAllocator>& v)
  {
    s << indent << "distance_l: ";
    Printer<double>::stream(s, indent + "  ", v.distance_l);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "preferred_distance_l: ";
    s << std::endl;
    Printer< ::decision_pb_msgs::Range_<ContainerAllocator> >::stream(s, indent + "  ", v.preferred_distance_l);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_PB_MSGS_MESSAGE_OBJECTNUDGE_H
