// Generated by gencpp from file decision_pb_msgs/StopLine.msg
// DO NOT EDIT!


#ifndef DECISION_PB_MSGS_MESSAGE_STOPLINE_H
#define DECISION_PB_MSGS_MESSAGE_STOPLINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace decision_pb_msgs
{
template <class ContainerAllocator>
struct StopLine_
{
  typedef StopLine_<ContainerAllocator> Type;

  StopLine_()
    : lane_id()
    , distance_s(0.0)  {
    }
  StopLine_(const ContainerAllocator& _alloc)
    : lane_id(_alloc)
    , distance_s(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lane_id_type;
  _lane_id_type lane_id;

   typedef double _distance_s_type;
  _distance_s_type distance_s;




  typedef boost::shared_ptr< ::decision_pb_msgs::StopLine_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision_pb_msgs::StopLine_<ContainerAllocator> const> ConstPtr;

}; // struct StopLine_

typedef ::decision_pb_msgs::StopLine_<std::allocator<void> > StopLine;

typedef boost::shared_ptr< ::decision_pb_msgs::StopLine > StopLinePtr;
typedef boost::shared_ptr< ::decision_pb_msgs::StopLine const> StopLineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision_pb_msgs::StopLine_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision_pb_msgs::StopLine_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision_pb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'perception_pb_msgs': ['/home/caros/ros/share/perception_pb_msgs/cmake/../msg'], 'prediction_pb_msgs': ['/home/caros/ros/share/prediction_pb_msgs/cmake/../msg'], 'decision_pb_msgs': ['/home/scmbuild/workspaces_cluster/baidu.adu.ros/baidu/adu/ros/pb_msgs/decision_pb_msgs/msg'], 'common_pb_msgs': ['/home/caros/ros/share/common_pb_msgs/cmake/../msg'], 'header_pb_msgs': ['/home/caros/ros/share/header_pb_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision_pb_msgs::StopLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision_pb_msgs::StopLine_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_pb_msgs::StopLine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_pb_msgs::StopLine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_pb_msgs::StopLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_pb_msgs::StopLine_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision_pb_msgs::StopLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a99f2b192572720b811e3cd16ac82b69";
  }

  static const char* value(const ::decision_pb_msgs::StopLine_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa99f2b192572720bULL;
  static const uint64_t static_value2 = 0x811e3cd16ac82b69ULL;
};

template<class ContainerAllocator>
struct DataType< ::decision_pb_msgs::StopLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision_pb_msgs/StopLine";
  }

  static const char* value(const ::decision_pb_msgs::StopLine_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision_pb_msgs::StopLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string lane_id \n\
float64 distance_s \n\
";
  }

  static const char* value(const ::decision_pb_msgs::StopLine_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision_pb_msgs::StopLine_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lane_id);
      stream.next(m.distance_s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct StopLine_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision_pb_msgs::StopLine_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision_pb_msgs::StopLine_<ContainerAllocator>& v)
  {
    s << indent << "lane_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lane_id);
    s << indent << "distance_s: ";
    Printer<double>::stream(s, indent + "  ", v.distance_s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_PB_MSGS_MESSAGE_STOPLINE_H
