// Generated by gencpp from file status_pb_msgs/Status.msg
// DO NOT EDIT!


#ifndef STATUS_PB_MSGS_MESSAGE_STATUS_H
#define STATUS_PB_MSGS_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <header_pb_msgs/Header.h>
#include <status_pb_msgs/Chassis.h>
#include <localization_pb_msgs/Pose.h>

namespace status_pb_msgs
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : header()
    , chassis()
    , pose()  {
    }
  Status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , chassis(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::header_pb_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::status_pb_msgs::Chassis_<ContainerAllocator>  _chassis_type;
  _chassis_type chassis;

   typedef  ::localization_pb_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::status_pb_msgs::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::status_pb_msgs::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::status_pb_msgs::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::status_pb_msgs::Status > StatusPtr;
typedef boost::shared_ptr< ::status_pb_msgs::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::status_pb_msgs::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::status_pb_msgs::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace status_pb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'localization_pb_msgs': ['/home/caros/ros/share/localization_pb_msgs/cmake/../msg'], 'common_pb_msgs': ['/home/caros/ros/share/common_pb_msgs/cmake/../msg'], 'status_pb_msgs': ['/home/scmbuild/workspaces_cluster.tmp/tmp.20161206.225249.22574/baidu/adu/ros/pb_msgs/status_pb_msgs/msg'], 'header_pb_msgs': ['/home/caros/ros/share/header_pb_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::status_pb_msgs::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::status_pb_msgs::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::status_pb_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::status_pb_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::status_pb_msgs::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::status_pb_msgs::Status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::status_pb_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c108e7cdb5158d560070b2d84145e09b";
  }

  static const char* value(const ::status_pb_msgs::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc108e7cdb5158d56ULL;
  static const uint64_t static_value2 = 0x0070b2d84145e09bULL;
};

template<class ContainerAllocator>
struct DataType< ::status_pb_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "status_pb_msgs/Status";
  }

  static const char* value(const ::status_pb_msgs::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::status_pb_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "header_pb_msgs/Header header \n\
Chassis chassis \n\
localization_pb_msgs/Pose pose \n\
\n\
================================================================================\n\
MSG: header_pb_msgs/Header\n\
float64 timestamp_sec \n\
string module_name \n\
uint32 sequence_num \n\
\n\
================================================================================\n\
MSG: status_pb_msgs/Chassis\n\
int32 driving_mode \n\
int32 error_code \n\
bool engine_started \n\
float32 engine_rpm \n\
float32 speed_mps \n\
float32 odometer_m \n\
int32 fuel_range_m \n\
float32 throttle_percentage \n\
float32 brake_percentage \n\
int32 gear_location \n\
float32 steering_percentage \n\
float32 steering_torque_nm \n\
bool parking_brake \n\
bool high_beam_signal \n\
bool low_beam_signal \n\
bool left_turn_signal \n\
bool right_turn_signal \n\
bool horn \n\
bool wiper \n\
\n\
================================================================================\n\
MSG: localization_pb_msgs/Pose\n\
common_pb_msgs/PointENU position \n\
common_pb_msgs/Quaternion orientation \n\
common_pb_msgs/Point3D linear_velocity \n\
common_pb_msgs/Point3D linear_acceleration \n\
common_pb_msgs/Point3D angular_velocity \n\
\n\
================================================================================\n\
MSG: common_pb_msgs/PointENU\n\
float64 x \n\
float64 y \n\
float64 z \n\
\n\
================================================================================\n\
MSG: common_pb_msgs/Quaternion\n\
float64 qx \n\
float64 qy \n\
float64 qz \n\
float64 qw \n\
\n\
================================================================================\n\
MSG: common_pb_msgs/Point3D\n\
float64 x \n\
float64 y \n\
float64 z \n\
";
  }

  static const char* value(const ::status_pb_msgs::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::status_pb_msgs::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.chassis);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::status_pb_msgs::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::status_pb_msgs::Status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::header_pb_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "chassis: ";
    s << std::endl;
    Printer< ::status_pb_msgs::Chassis_<ContainerAllocator> >::stream(s, indent + "  ", v.chassis);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::localization_pb_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATUS_PB_MSGS_MESSAGE_STATUS_H
