// Generated by gencpp from file routing_pb_msgs/LaneWaypoint.msg
// DO NOT EDIT!


#ifndef ROUTING_PB_MSGS_MESSAGE_LANEWAYPOINT_H
#define ROUTING_PB_MSGS_MESSAGE_LANEWAYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <routing_pb_msgs/Pose.h>

namespace routing_pb_msgs
{
template <class ContainerAllocator>
struct LaneWaypoint_
{
  typedef LaneWaypoint_<ContainerAllocator> Type;

  LaneWaypoint_()
    : id()
    , s(0.0)
    , pose()  {
    }
  LaneWaypoint_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , s(0.0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef double _s_type;
  _s_type s;

   typedef  ::routing_pb_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> const> ConstPtr;

}; // struct LaneWaypoint_

typedef ::routing_pb_msgs::LaneWaypoint_<std::allocator<void> > LaneWaypoint;

typedef boost::shared_ptr< ::routing_pb_msgs::LaneWaypoint > LaneWaypointPtr;
typedef boost::shared_ptr< ::routing_pb_msgs::LaneWaypoint const> LaneWaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace routing_pb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'routing_pb_msgs': ['/home/scmbuild/workspaces_cluster/baidu.adu.ros/baidu/adu/ros/pb_msgs/routing_pb_msgs/msg'], 'common_pb_msgs': ['/home/caros/ros/share/common_pb_msgs/cmake/../msg'], 'header_pb_msgs': ['/home/caros/ros/share/header_pb_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fad686053627fc458de75e74f7ec519d";
  }

  static const char* value(const ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfad686053627fc45ULL;
  static const uint64_t static_value2 = 0x8de75e74f7ec519dULL;
};

template<class ContainerAllocator>
struct DataType< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "routing_pb_msgs/LaneWaypoint";
  }

  static const char* value(const ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id \n\
float64 s \n\
Pose pose \n\
\n\
================================================================================\n\
MSG: routing_pb_msgs/Pose\n\
float64 x \n\
float64 y \n\
";
  }

  static const char* value(const ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.s);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct LaneWaypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::routing_pb_msgs::LaneWaypoint_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "s: ";
    Printer<double>::stream(s, indent + "  ", v.s);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::routing_pb_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROUTING_PB_MSGS_MESSAGE_LANEWAYPOINT_H
