// Generated by gencpp from file hdmap_pb_msgs/Arc.msg
// DO NOT EDIT!


#ifndef HDMAP_PB_MSGS_MESSAGE_ARC_H
#define HDMAP_PB_MSGS_MESSAGE_ARC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hdmap_pb_msgs/Point.h>

namespace hdmap_pb_msgs
{
template <class ContainerAllocator>
struct Arc_
{
  typedef Arc_<ContainerAllocator> Type;

  Arc_()
    : center()
    , radius(0.0)
    , start_angle(0.0)
    , end_angle(0.0)  {
    }
  Arc_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , radius(0.0)
    , start_angle(0.0)
    , end_angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::hdmap_pb_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef double _radius_type;
  _radius_type radius;

   typedef double _start_angle_type;
  _start_angle_type start_angle;

   typedef double _end_angle_type;
  _end_angle_type end_angle;




  typedef boost::shared_ptr< ::hdmap_pb_msgs::Arc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdmap_pb_msgs::Arc_<ContainerAllocator> const> ConstPtr;

}; // struct Arc_

typedef ::hdmap_pb_msgs::Arc_<std::allocator<void> > Arc;

typedef boost::shared_ptr< ::hdmap_pb_msgs::Arc > ArcPtr;
typedef boost::shared_ptr< ::hdmap_pb_msgs::Arc const> ArcConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdmap_pb_msgs::Arc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdmap_pb_msgs::Arc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hdmap_pb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'common_pb_msgs': ['/home/caros/ros/share/common_pb_msgs/cmake/../msg'], 'hdmap_pb_msgs': ['/home/scmbuild/workspaces_cluster.tmp/tmp.20161206.225249.22574/baidu/adu/ros/pb_msgs/hdmap_pb_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hdmap_pb_msgs::Arc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdmap_pb_msgs::Arc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdmap_pb_msgs::Arc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdmap_pb_msgs::Arc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdmap_pb_msgs::Arc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdmap_pb_msgs::Arc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdmap_pb_msgs::Arc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db655184aa920508892b27ecab920c46";
  }

  static const char* value(const ::hdmap_pb_msgs::Arc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb655184aa920508ULL;
  static const uint64_t static_value2 = 0x892b27ecab920c46ULL;
};

template<class ContainerAllocator>
struct DataType< ::hdmap_pb_msgs::Arc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdmap_pb_msgs/Arc";
  }

  static const char* value(const ::hdmap_pb_msgs::Arc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdmap_pb_msgs::Arc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point center \n\
float64 radius \n\
float64 start_angle \n\
float64 end_angle \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Point\n\
float64 x \n\
float64 y \n\
float64 z \n\
";
  }

  static const char* value(const ::hdmap_pb_msgs::Arc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdmap_pb_msgs::Arc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.radius);
      stream.next(m.start_angle);
      stream.next(m.end_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Arc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdmap_pb_msgs::Arc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdmap_pb_msgs::Arc_<ContainerAllocator>& v)
  {
    s << indent << "center: ";
    s << std::endl;
    Printer< ::hdmap_pb_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
    s << indent << "start_angle: ";
    Printer<double>::stream(s, indent + "  ", v.start_angle);
    s << indent << "end_angle: ";
    Printer<double>::stream(s, indent + "  ", v.end_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_PB_MSGS_MESSAGE_ARC_H
