// Generated by gencpp from file hdmap_pb_msgs/CrosswalkOverlapInfo.msg
// DO NOT EDIT!


#ifndef HDMAP_PB_MSGS_MESSAGE_CROSSWALKOVERLAPINFO_H
#define HDMAP_PB_MSGS_MESSAGE_CROSSWALKOVERLAPINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hdmap_pb_msgs
{
template <class ContainerAllocator>
struct CrosswalkOverlapInfo_
{
  typedef CrosswalkOverlapInfo_<ContainerAllocator> Type;

  CrosswalkOverlapInfo_()
    {
    }
  CrosswalkOverlapInfo_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> const> ConstPtr;

}; // struct CrosswalkOverlapInfo_

typedef ::hdmap_pb_msgs::CrosswalkOverlapInfo_<std::allocator<void> > CrosswalkOverlapInfo;

typedef boost::shared_ptr< ::hdmap_pb_msgs::CrosswalkOverlapInfo > CrosswalkOverlapInfoPtr;
typedef boost::shared_ptr< ::hdmap_pb_msgs::CrosswalkOverlapInfo const> CrosswalkOverlapInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hdmap_pb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'common_pb_msgs': ['/home/caros/ros/share/common_pb_msgs/cmake/../msg'], 'hdmap_pb_msgs': ['/home/scmbuild/workspaces_cluster.tmp/tmp.20161206.225249.22574/baidu/adu/ros/pb_msgs/hdmap_pb_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdmap_pb_msgs/CrosswalkOverlapInfo";
  }

  static const char* value(const ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CrosswalkOverlapInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::hdmap_pb_msgs::CrosswalkOverlapInfo_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_PB_MSGS_MESSAGE_CROSSWALKOVERLAPINFO_H
