// Generated by gencpp from file hdmap_pb_msgs/LaneOverlapInfo.msg
// DO NOT EDIT!


#ifndef HDMAP_PB_MSGS_MESSAGE_LANEOVERLAPINFO_H
#define HDMAP_PB_MSGS_MESSAGE_LANEOVERLAPINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hdmap_pb_msgs
{
template <class ContainerAllocator>
struct LaneOverlapInfo_
{
  typedef LaneOverlapInfo_<ContainerAllocator> Type;

  LaneOverlapInfo_()
    : start_s(0.0)
    , end_s(0.0)
    , is_merge(false)
    , has_precedence(false)  {
    }
  LaneOverlapInfo_(const ContainerAllocator& _alloc)
    : start_s(0.0)
    , end_s(0.0)
    , is_merge(false)
    , has_precedence(false)  {
  (void)_alloc;
    }



   typedef double _start_s_type;
  _start_s_type start_s;

   typedef double _end_s_type;
  _end_s_type end_s;

   typedef uint8_t _is_merge_type;
  _is_merge_type is_merge;

   typedef uint8_t _has_precedence_type;
  _has_precedence_type has_precedence;




  typedef boost::shared_ptr< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> const> ConstPtr;

}; // struct LaneOverlapInfo_

typedef ::hdmap_pb_msgs::LaneOverlapInfo_<std::allocator<void> > LaneOverlapInfo;

typedef boost::shared_ptr< ::hdmap_pb_msgs::LaneOverlapInfo > LaneOverlapInfoPtr;
typedef boost::shared_ptr< ::hdmap_pb_msgs::LaneOverlapInfo const> LaneOverlapInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hdmap_pb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'common_pb_msgs': ['/home/caros/ros/share/common_pb_msgs/cmake/../msg'], 'hdmap_pb_msgs': ['/home/scmbuild/workspaces_cluster/baidu.adu.ros/baidu/adu/ros/pb_msgs/hdmap_pb_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03d30d4f798ccf751f91603c8963a348";
  }

  static const char* value(const ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03d30d4f798ccf75ULL;
  static const uint64_t static_value2 = 0x1f91603c8963a348ULL;
};

template<class ContainerAllocator>
struct DataType< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdmap_pb_msgs/LaneOverlapInfo";
  }

  static const char* value(const ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 start_s \n\
float64 end_s \n\
bool is_merge \n\
bool has_precedence \n\
";
  }

  static const char* value(const ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_s);
      stream.next(m.end_s);
      stream.next(m.is_merge);
      stream.next(m.has_precedence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct LaneOverlapInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdmap_pb_msgs::LaneOverlapInfo_<ContainerAllocator>& v)
  {
    s << indent << "start_s: ";
    Printer<double>::stream(s, indent + "  ", v.start_s);
    s << indent << "end_s: ";
    Printer<double>::stream(s, indent + "  ", v.end_s);
    s << indent << "is_merge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_merge);
    s << indent << "has_precedence: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_precedence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_PB_MSGS_MESSAGE_LANEOVERLAPINFO_H
