// Generated by gencpp from file hdmap_pb_msgs/Signal.msg
// DO NOT EDIT!


#ifndef HDMAP_PB_MSGS_MESSAGE_SIGNAL_H
#define HDMAP_PB_MSGS_MESSAGE_SIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hdmap_pb_msgs/Id.h>
#include <hdmap_pb_msgs/Polygon.h>
#include <hdmap_pb_msgs/Subsignal.h>
#include <hdmap_pb_msgs/Id.h>
#include <hdmap_pb_msgs/Curve.h>

namespace hdmap_pb_msgs
{
template <class ContainerAllocator>
struct Signal_
{
  typedef Signal_<ContainerAllocator> Type;

  Signal_()
    : id()
    , boundary()
    , subsignal()
    , overlap_id()
    , type(0)
    , stop_line()  {
    }
  Signal_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , boundary(_alloc)
    , subsignal(_alloc)
    , overlap_id(_alloc)
    , type(0)
    , stop_line(_alloc)  {
  (void)_alloc;
    }



   typedef  ::hdmap_pb_msgs::Id_<ContainerAllocator>  _id_type;
  _id_type id;

   typedef  ::hdmap_pb_msgs::Polygon_<ContainerAllocator>  _boundary_type;
  _boundary_type boundary;

   typedef std::vector< ::hdmap_pb_msgs::Subsignal_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hdmap_pb_msgs::Subsignal_<ContainerAllocator> >::other >  _subsignal_type;
  _subsignal_type subsignal;

   typedef std::vector< ::hdmap_pb_msgs::Id_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hdmap_pb_msgs::Id_<ContainerAllocator> >::other >  _overlap_id_type;
  _overlap_id_type overlap_id;

   typedef int32_t _type_type;
  _type_type type;

   typedef std::vector< ::hdmap_pb_msgs::Curve_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hdmap_pb_msgs::Curve_<ContainerAllocator> >::other >  _stop_line_type;
  _stop_line_type stop_line;




  typedef boost::shared_ptr< ::hdmap_pb_msgs::Signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdmap_pb_msgs::Signal_<ContainerAllocator> const> ConstPtr;

}; // struct Signal_

typedef ::hdmap_pb_msgs::Signal_<std::allocator<void> > Signal;

typedef boost::shared_ptr< ::hdmap_pb_msgs::Signal > SignalPtr;
typedef boost::shared_ptr< ::hdmap_pb_msgs::Signal const> SignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdmap_pb_msgs::Signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdmap_pb_msgs::Signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hdmap_pb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'common_pb_msgs': ['/home/caros/ros/share/common_pb_msgs/cmake/../msg'], 'hdmap_pb_msgs': ['/home/scmbuild/workspaces_cluster/baidu.adu.ros/baidu/adu/ros/pb_msgs/hdmap_pb_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hdmap_pb_msgs::Signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdmap_pb_msgs::Signal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdmap_pb_msgs::Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdmap_pb_msgs::Signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdmap_pb_msgs::Signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdmap_pb_msgs::Signal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdmap_pb_msgs::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa6df01c6aad20d364660ddf75a2c1c5";
  }

  static const char* value(const ::hdmap_pb_msgs::Signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa6df01c6aad20d3ULL;
  static const uint64_t static_value2 = 0x64660ddf75a2c1c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::hdmap_pb_msgs::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdmap_pb_msgs/Signal";
  }

  static const char* value(const ::hdmap_pb_msgs::Signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdmap_pb_msgs::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Id id \n\
Polygon boundary \n\
Subsignal[] subsignal \n\
Id[] overlap_id \n\
int32 type \n\
Curve[] stop_line \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Id\n\
int8 id \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Polygon\n\
Point[] point \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Point\n\
float64 x \n\
float64 y \n\
float64 z \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Subsignal\n\
Id id \n\
int32 type \n\
Point location \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Curve\n\
CurveSegment[] segment \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/CurveSegment\n\
LineSegment line_segment \n\
Arc arc \n\
Spiral spiral \n\
Spline spline \n\
Poly3 poly3 \n\
float64 s \n\
Point start_position \n\
float64 heading \n\
float64 length \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/LineSegment\n\
Point[] point \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Arc\n\
Point center \n\
float64 radius \n\
float64 start_angle \n\
float64 end_angle \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Spiral\n\
float64 curv_start \n\
float64 curv_end \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Spline\n\
int32 dimension \n\
int32 degree \n\
float64[] knot \n\
Point[] control \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Poly3\n\
";
  }

  static const char* value(const ::hdmap_pb_msgs::Signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdmap_pb_msgs::Signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.boundary);
      stream.next(m.subsignal);
      stream.next(m.overlap_id);
      stream.next(m.type);
      stream.next(m.stop_line);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdmap_pb_msgs::Signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdmap_pb_msgs::Signal_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    s << std::endl;
    Printer< ::hdmap_pb_msgs::Id_<ContainerAllocator> >::stream(s, indent + "  ", v.id);
    s << indent << "boundary: ";
    s << std::endl;
    Printer< ::hdmap_pb_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.boundary);
    s << indent << "subsignal[]" << std::endl;
    for (size_t i = 0; i < v.subsignal.size(); ++i)
    {
      s << indent << "  subsignal[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hdmap_pb_msgs::Subsignal_<ContainerAllocator> >::stream(s, indent + "    ", v.subsignal[i]);
    }
    s << indent << "overlap_id[]" << std::endl;
    for (size_t i = 0; i < v.overlap_id.size(); ++i)
    {
      s << indent << "  overlap_id[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hdmap_pb_msgs::Id_<ContainerAllocator> >::stream(s, indent + "    ", v.overlap_id[i]);
    }
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "stop_line[]" << std::endl;
    for (size_t i = 0; i < v.stop_line.size(); ++i)
    {
      s << indent << "  stop_line[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hdmap_pb_msgs::Curve_<ContainerAllocator> >::stream(s, indent + "    ", v.stop_line[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_PB_MSGS_MESSAGE_SIGNAL_H
