// Generated by gencpp from file hdmap_pb_msgs/Spline.msg
// DO NOT EDIT!


#ifndef HDMAP_PB_MSGS_MESSAGE_SPLINE_H
#define HDMAP_PB_MSGS_MESSAGE_SPLINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hdmap_pb_msgs/Point.h>

namespace hdmap_pb_msgs
{
template <class ContainerAllocator>
struct Spline_
{
  typedef Spline_<ContainerAllocator> Type;

  Spline_()
    : dimension(0)
    , degree(0)
    , knot()
    , control()  {
    }
  Spline_(const ContainerAllocator& _alloc)
    : dimension(0)
    , degree(0)
    , knot(_alloc)
    , control(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _dimension_type;
  _dimension_type dimension;

   typedef int32_t _degree_type;
  _degree_type degree;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _knot_type;
  _knot_type knot;

   typedef std::vector< ::hdmap_pb_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hdmap_pb_msgs::Point_<ContainerAllocator> >::other >  _control_type;
  _control_type control;




  typedef boost::shared_ptr< ::hdmap_pb_msgs::Spline_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hdmap_pb_msgs::Spline_<ContainerAllocator> const> ConstPtr;

}; // struct Spline_

typedef ::hdmap_pb_msgs::Spline_<std::allocator<void> > Spline;

typedef boost::shared_ptr< ::hdmap_pb_msgs::Spline > SplinePtr;
typedef boost::shared_ptr< ::hdmap_pb_msgs::Spline const> SplineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hdmap_pb_msgs::Spline_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hdmap_pb_msgs::Spline_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hdmap_pb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'common_pb_msgs': ['/home/caros/ros/share/common_pb_msgs/cmake/../msg'], 'hdmap_pb_msgs': ['/home/scmbuild/workspaces_cluster.tmp/tmp.20161206.225249.22574/baidu/adu/ros/pb_msgs/hdmap_pb_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hdmap_pb_msgs::Spline_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hdmap_pb_msgs::Spline_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdmap_pb_msgs::Spline_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hdmap_pb_msgs::Spline_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdmap_pb_msgs::Spline_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hdmap_pb_msgs::Spline_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hdmap_pb_msgs::Spline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7093b5f795127af1d1f971334132cd3";
  }

  static const char* value(const ::hdmap_pb_msgs::Spline_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7093b5f795127afULL;
  static const uint64_t static_value2 = 0x1d1f971334132cd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::hdmap_pb_msgs::Spline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hdmap_pb_msgs/Spline";
  }

  static const char* value(const ::hdmap_pb_msgs::Spline_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hdmap_pb_msgs::Spline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 dimension \n\
int32 degree \n\
float64[] knot \n\
Point[] control \n\
\n\
================================================================================\n\
MSG: hdmap_pb_msgs/Point\n\
float64 x \n\
float64 y \n\
float64 z \n\
";
  }

  static const char* value(const ::hdmap_pb_msgs::Spline_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hdmap_pb_msgs::Spline_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dimension);
      stream.next(m.degree);
      stream.next(m.knot);
      stream.next(m.control);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Spline_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hdmap_pb_msgs::Spline_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hdmap_pb_msgs::Spline_<ContainerAllocator>& v)
  {
    s << indent << "dimension: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dimension);
    s << indent << "degree: ";
    Printer<int32_t>::stream(s, indent + "  ", v.degree);
    s << indent << "knot[]" << std::endl;
    for (size_t i = 0; i < v.knot.size(); ++i)
    {
      s << indent << "  knot[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.knot[i]);
    }
    s << indent << "control[]" << std::endl;
    for (size_t i = 0; i < v.control.size(); ++i)
    {
      s << indent << "  control[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hdmap_pb_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.control[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HDMAP_PB_MSGS_MESSAGE_SPLINE_H
