// Generated by gencpp from file traffic_light_pb_msgs/TrafficLightDetection.msg
// DO NOT EDIT!


#ifndef TRAFFIC_LIGHT_PB_MSGS_MESSAGE_TRAFFICLIGHTDETECTION_H
#define TRAFFIC_LIGHT_PB_MSGS_MESSAGE_TRAFFICLIGHTDETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <header_pb_msgs/Header.h>
#include <traffic_light_pb_msgs/TrafficLight.h>

namespace traffic_light_pb_msgs
{
template <class ContainerAllocator>
struct TrafficLightDetection_
{
  typedef TrafficLightDetection_<ContainerAllocator> Type;

  TrafficLightDetection_()
    : header()
    , traffic_light()  {
    }
  TrafficLightDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , traffic_light(_alloc)  {
  (void)_alloc;
    }



   typedef  ::header_pb_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::traffic_light_pb_msgs::TrafficLight_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::traffic_light_pb_msgs::TrafficLight_<ContainerAllocator> >::other >  _traffic_light_type;
  _traffic_light_type traffic_light;




  typedef boost::shared_ptr< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLightDetection_

typedef ::traffic_light_pb_msgs::TrafficLightDetection_<std::allocator<void> > TrafficLightDetection;

typedef boost::shared_ptr< ::traffic_light_pb_msgs::TrafficLightDetection > TrafficLightDetectionPtr;
typedef boost::shared_ptr< ::traffic_light_pb_msgs::TrafficLightDetection const> TrafficLightDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace traffic_light_pb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'traffic_light_pb_msgs': ['/home/scmbuild/workspaces_cluster.tmp/tmp.20161206.225249.22574/baidu/adu/ros/pb_msgs/traffic_light_pb_msgs/msg'], 'common_pb_msgs': ['/home/caros/ros/share/common_pb_msgs/cmake/../msg'], 'header_pb_msgs': ['/home/caros/ros/share/header_pb_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f68f87c15857288408ca744423b3735";
  }

  static const char* value(const ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f68f87c15857288ULL;
  static const uint64_t static_value2 = 0x408ca744423b3735ULL;
};

template<class ContainerAllocator>
struct DataType< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traffic_light_pb_msgs/TrafficLightDetection";
  }

  static const char* value(const ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "header_pb_msgs/Header header \n\
TrafficLight[] traffic_light \n\
\n\
================================================================================\n\
MSG: header_pb_msgs/Header\n\
float64 timestamp_sec \n\
string module_name \n\
uint32 sequence_num \n\
\n\
================================================================================\n\
MSG: traffic_light_pb_msgs/TrafficLight\n\
int32 color \n\
string id \n\
float64 confidence \n\
float64 tracking_time \n\
";
  }

  static const char* value(const ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.traffic_light);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TrafficLightDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traffic_light_pb_msgs::TrafficLightDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::header_pb_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "traffic_light[]" << std::endl;
    for (size_t i = 0; i < v.traffic_light.size(); ++i)
    {
      s << indent << "  traffic_light[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::traffic_light_pb_msgs::TrafficLight_<ContainerAllocator> >::stream(s, indent + "    ", v.traffic_light[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAFFIC_LIGHT_PB_MSGS_MESSAGE_TRAFFICLIGHTDETECTION_H
