# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hdmap_pb_msgs/Arc.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hdmap_pb_msgs.msg

class Arc(genpy.Message):
  _md5sum = "db655184aa920508892b27ecab920c46"
  _type = "hdmap_pb_msgs/Arc"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Point center 
float64 radius 
float64 start_angle 
float64 end_angle 

================================================================================
MSG: hdmap_pb_msgs/Point
float64 x 
float64 y 
float64 z 
"""
  __slots__ = ['center','radius','start_angle','end_angle']
  _slot_types = ['hdmap_pb_msgs/Point','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       center,radius,start_angle,end_angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Arc, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.center is None:
        self.center = hdmap_pb_msgs.msg.Point()
      if self.radius is None:
        self.radius = 0.
      if self.start_angle is None:
        self.start_angle = 0.
      if self.end_angle is None:
        self.end_angle = 0.
    else:
      self.center = hdmap_pb_msgs.msg.Point()
      self.radius = 0.
      self.start_angle = 0.
      self.end_angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.center.x, _x.center.y, _x.center.z, _x.radius, _x.start_angle, _x.end_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.center is None:
        self.center = hdmap_pb_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.center.x, _x.center.y, _x.center.z, _x.radius, _x.start_angle, _x.end_angle,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.center.x, _x.center.y, _x.center.z, _x.radius, _x.start_angle, _x.end_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.center is None:
        self.center = hdmap_pb_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.center.x, _x.center.y, _x.center.z, _x.radius, _x.start_angle, _x.end_angle,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
