# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hdmap_pb_msgs/StopSign.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hdmap_pb_msgs.msg

class StopSign(genpy.Message):
  _md5sum = "575b3327bee5b8682ea461e04d308069"
  _type = "hdmap_pb_msgs/StopSign"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Id id 
Curve stop_line 
Point location 
Id[] overlap_id 
Id signal_id 

================================================================================
MSG: hdmap_pb_msgs/Id
int8 id 

================================================================================
MSG: hdmap_pb_msgs/Curve
CurveSegment[] segment 

================================================================================
MSG: hdmap_pb_msgs/CurveSegment
LineSegment line_segment 
Arc arc 
Spiral spiral 
Spline spline 
Poly3 poly3 
float64 s 
Point start_position 
float64 heading 
float64 length 

================================================================================
MSG: hdmap_pb_msgs/LineSegment
Point[] point 

================================================================================
MSG: hdmap_pb_msgs/Point
float64 x 
float64 y 
float64 z 

================================================================================
MSG: hdmap_pb_msgs/Arc
Point center 
float64 radius 
float64 start_angle 
float64 end_angle 

================================================================================
MSG: hdmap_pb_msgs/Spiral
float64 curv_start 
float64 curv_end 

================================================================================
MSG: hdmap_pb_msgs/Spline
int32 dimension 
int32 degree 
float64[] knot 
Point[] control 

================================================================================
MSG: hdmap_pb_msgs/Poly3
"""
  __slots__ = ['id','stop_line','location','overlap_id','signal_id']
  _slot_types = ['hdmap_pb_msgs/Id','hdmap_pb_msgs/Curve','hdmap_pb_msgs/Point','hdmap_pb_msgs/Id[]','hdmap_pb_msgs/Id']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,stop_line,location,overlap_id,signal_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StopSign, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = hdmap_pb_msgs.msg.Id()
      if self.stop_line is None:
        self.stop_line = hdmap_pb_msgs.msg.Curve()
      if self.location is None:
        self.location = hdmap_pb_msgs.msg.Point()
      if self.overlap_id is None:
        self.overlap_id = []
      if self.signal_id is None:
        self.signal_id = hdmap_pb_msgs.msg.Id()
    else:
      self.id = hdmap_pb_msgs.msg.Id()
      self.stop_line = hdmap_pb_msgs.msg.Curve()
      self.location = hdmap_pb_msgs.msg.Point()
      self.overlap_id = []
      self.signal_id = hdmap_pb_msgs.msg.Id()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_b.pack(self.id.id))
      length = len(self.stop_line.segment)
      buff.write(_struct_I.pack(length))
      for val1 in self.stop_line.segment:
        _v1 = val1.line_segment
        length = len(_v1.point)
        buff.write(_struct_I.pack(length))
        for val3 in _v1.point:
          _x = val3
          buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v2 = val1.arc
        _v3 = _v2.center
        _x = _v3
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _x = _v2
        buff.write(_struct_3d.pack(_x.radius, _x.start_angle, _x.end_angle))
        _v4 = val1.spiral
        _x = _v4
        buff.write(_struct_2d.pack(_x.curv_start, _x.curv_end))
        _v5 = val1.spline
        _x = _v5
        buff.write(_struct_2i.pack(_x.dimension, _x.degree))
        length = len(_v5.knot)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.pack(pattern, *_v5.knot))
        length = len(_v5.control)
        buff.write(_struct_I.pack(length))
        for val3 in _v5.control:
          _x = val3
          buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v6 = val1.poly3
        pass
        buff.write(_struct_d.pack(val1.s))
        _v7 = val1.start_position
        _x = _v7
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_struct_2d.pack(_x.heading, _x.length))
      _x = self
      buff.write(_struct_3d.pack(_x.location.x, _x.location.y, _x.location.z))
      length = len(self.overlap_id)
      buff.write(_struct_I.pack(length))
      for val1 in self.overlap_id:
        buff.write(_struct_b.pack(val1.id))
      buff.write(_struct_b.pack(self.signal_id.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.id is None:
        self.id = hdmap_pb_msgs.msg.Id()
      if self.stop_line is None:
        self.stop_line = hdmap_pb_msgs.msg.Curve()
      if self.location is None:
        self.location = hdmap_pb_msgs.msg.Point()
      if self.overlap_id is None:
        self.overlap_id = None
      if self.signal_id is None:
        self.signal_id = hdmap_pb_msgs.msg.Id()
      end = 0
      start = end
      end += 1
      (self.id.id,) = _struct_b.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.stop_line.segment = []
      for i in range(0, length):
        val1 = hdmap_pb_msgs.msg.CurveSegment()
        _v8 = val1.line_segment
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v8.point = []
        for i in range(0, length):
          val3 = hdmap_pb_msgs.msg.Point()
          _x = val3
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
          _v8.point.append(val3)
        _v9 = val1.arc
        _v10 = _v9.center
        _x = _v10
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _x = _v9
        start = end
        end += 24
        (_x.radius, _x.start_angle, _x.end_angle,) = _struct_3d.unpack(str[start:end])
        _v11 = val1.spiral
        _x = _v11
        start = end
        end += 16
        (_x.curv_start, _x.curv_end,) = _struct_2d.unpack(str[start:end])
        _v12 = val1.spline
        _x = _v12
        start = end
        end += 8
        (_x.dimension, _x.degree,) = _struct_2i.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        end += struct.calcsize(pattern)
        _v12.knot = struct.unpack(pattern, str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v12.control = []
        for i in range(0, length):
          val3 = hdmap_pb_msgs.msg.Point()
          _x = val3
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
          _v12.control.append(val3)
        _v13 = val1.poly3
        start = end
        end += 8
        (val1.s,) = _struct_d.unpack(str[start:end])
        _v14 = val1.start_position
        _x = _v14
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _x = val1
        start = end
        end += 16
        (_x.heading, _x.length,) = _struct_2d.unpack(str[start:end])
        self.stop_line.segment.append(val1)
      _x = self
      start = end
      end += 24
      (_x.location.x, _x.location.y, _x.location.z,) = _struct_3d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.overlap_id = []
      for i in range(0, length):
        val1 = hdmap_pb_msgs.msg.Id()
        start = end
        end += 1
        (val1.id,) = _struct_b.unpack(str[start:end])
        self.overlap_id.append(val1)
      start = end
      end += 1
      (self.signal_id.id,) = _struct_b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_b.pack(self.id.id))
      length = len(self.stop_line.segment)
      buff.write(_struct_I.pack(length))
      for val1 in self.stop_line.segment:
        _v15 = val1.line_segment
        length = len(_v15.point)
        buff.write(_struct_I.pack(length))
        for val3 in _v15.point:
          _x = val3
          buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v16 = val1.arc
        _v17 = _v16.center
        _x = _v17
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _x = _v16
        buff.write(_struct_3d.pack(_x.radius, _x.start_angle, _x.end_angle))
        _v18 = val1.spiral
        _x = _v18
        buff.write(_struct_2d.pack(_x.curv_start, _x.curv_end))
        _v19 = val1.spline
        _x = _v19
        buff.write(_struct_2i.pack(_x.dimension, _x.degree))
        length = len(_v19.knot)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(_v19.knot.tostring())
        length = len(_v19.control)
        buff.write(_struct_I.pack(length))
        for val3 in _v19.control:
          _x = val3
          buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v20 = val1.poly3
        pass
        buff.write(_struct_d.pack(val1.s))
        _v21 = val1.start_position
        _x = _v21
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_struct_2d.pack(_x.heading, _x.length))
      _x = self
      buff.write(_struct_3d.pack(_x.location.x, _x.location.y, _x.location.z))
      length = len(self.overlap_id)
      buff.write(_struct_I.pack(length))
      for val1 in self.overlap_id:
        buff.write(_struct_b.pack(val1.id))
      buff.write(_struct_b.pack(self.signal_id.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.id is None:
        self.id = hdmap_pb_msgs.msg.Id()
      if self.stop_line is None:
        self.stop_line = hdmap_pb_msgs.msg.Curve()
      if self.location is None:
        self.location = hdmap_pb_msgs.msg.Point()
      if self.overlap_id is None:
        self.overlap_id = None
      if self.signal_id is None:
        self.signal_id = hdmap_pb_msgs.msg.Id()
      end = 0
      start = end
      end += 1
      (self.id.id,) = _struct_b.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.stop_line.segment = []
      for i in range(0, length):
        val1 = hdmap_pb_msgs.msg.CurveSegment()
        _v22 = val1.line_segment
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v22.point = []
        for i in range(0, length):
          val3 = hdmap_pb_msgs.msg.Point()
          _x = val3
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
          _v22.point.append(val3)
        _v23 = val1.arc
        _v24 = _v23.center
        _x = _v24
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _x = _v23
        start = end
        end += 24
        (_x.radius, _x.start_angle, _x.end_angle,) = _struct_3d.unpack(str[start:end])
        _v25 = val1.spiral
        _x = _v25
        start = end
        end += 16
        (_x.curv_start, _x.curv_end,) = _struct_2d.unpack(str[start:end])
        _v26 = val1.spline
        _x = _v26
        start = end
        end += 8
        (_x.dimension, _x.degree,) = _struct_2i.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        end += struct.calcsize(pattern)
        _v26.knot = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v26.control = []
        for i in range(0, length):
          val3 = hdmap_pb_msgs.msg.Point()
          _x = val3
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
          _v26.control.append(val3)
        _v27 = val1.poly3
        start = end
        end += 8
        (val1.s,) = _struct_d.unpack(str[start:end])
        _v28 = val1.start_position
        _x = _v28
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _x = val1
        start = end
        end += 16
        (_x.heading, _x.length,) = _struct_2d.unpack(str[start:end])
        self.stop_line.segment.append(val1)
      _x = self
      start = end
      end += 24
      (_x.location.x, _x.location.y, _x.location.z,) = _struct_3d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.overlap_id = []
      for i in range(0, length):
        val1 = hdmap_pb_msgs.msg.Id()
        start = end
        end += 1
        (val1.id,) = _struct_b.unpack(str[start:end])
        self.overlap_id.append(val1)
      start = end
      end += 1
      (self.signal_id.id,) = _struct_b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2d = struct.Struct("<2d")
_struct_d = struct.Struct("<d")
_struct_b = struct.Struct("<b")
_struct_2i = struct.Struct("<2i")
_struct_3d = struct.Struct("<3d")
