(cl:in-package hdmap_pb_msgs-msg)
(cl:export '(ID-VAL
          ID
          LANE_OVERLAP_INFO-VAL
          LANE_OVERLAP_INFO
          SIGNAL_OVERLAP_INFO-VAL
          SIGNAL_OVERLAP_INFO
          STOP_SIGN_OVERLAP_INFO-VAL
          STOP_SIGN_OVERLAP_INFO
          CROSSWALK_OVERLAP_INFO-VAL
          CROSSWALK_OVERLAP_INFO
          JUNCTION_OVERLAP_INFO-VAL
          JUNCTION_OVERLAP_INFO
))