(cl:in-package hdmap_pb_msgs-msg)
(cl:export '(ID-VAL
          ID
          TYPE-VAL
          TYPE
          TURN-VAL
          TURN
          CENTRAL_CURVE-VAL
          CENTRAL_CURVE
          LEFT_BOUNDARY-VAL
          LEFT_BOUNDARY
          RIGHT_BOUNDARY-VAL
          RIGHT_BOUNDARY
          WIDTH-VAL
          WIDTH
          LENGTH-VAL
          LENGTH
          SPEED_LIMIT-VAL
          SPEED_LIMIT
          OVERLAP_ID-VAL
          OVERLAP_ID
          PREDECESSOR_ID-VAL
          PREDECESSOR_ID
          SUCCESSOR_ID-VAL
          SUCCESSOR_ID
          LEFT_NEIGHBOR_FORWARD_LANE_ID-VAL
          LEFT_NEIGHBOR_FORWARD_LANE_ID
          RIGHT_NEIGHBOR_FORWARD_LANE_ID-VAL
          RIGHT_NEIGHBOR_FORWARD_LANE_ID
          LEFT_NEIGHBOR_REVERSE_LANE_ID-VAL
          LEFT_NEIGHBOR_REVERSE_LANE_ID
          RIGHT_NEIGHBOR_REVERSE_LANE_ID-VAL
          RIGHT_NEIGHBOR_REVERSE_LANE_ID
          STOP_SIGN_ID-VAL
          STOP_SIGN_ID
          JUNCTION_ID-VAL
          JUNCTION_ID
          CROSSWALK_ID-VAL
          CROSSWALK_ID
          YIELD_SIGN_ID-VAL
          YIELD_SIGN_ID
          LEFT_SAMPLE-VAL
          LEFT_SAMPLE
          RIGHT_SAMPLE-VAL
          RIGHT_SAMPLE
))