SET(CUR_LIB_NAME "boost")
#SET(CUR_LIB_PATH "${PROJECT_THIRD_PATH}/${CUR_LIB_NAME}")
#SET(CMAKE_PREFIX_PATH ${CUR_LIB_PATH})

#/usr/share/cmake-2.8/Modules/FindBoost.cmake
FIND_PACKAGE(Boost 1.5.4 REQUIRED)

INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS})
LINK_DIRECTORIES(${Boost_LIBRARY_DIRS})
SET(PROJECT_THIRD_LIBS ${PROJECT_THIRD_LIBS} ${Boost_LIBRARIES})
