SET(CUR_LIB_NAME "caffe")
SET(CUR_LIB_PATH "${PROJECT_THIRD_PATH}/${CUR_LIB_NAME}")
SET(CMAKE_PREFIX_PATH ${CUR_LIB_PATH})

FIND_PACKAGE(Caffe REQUIRED)

INCLUDE_DIRECTORIES(${Caffe_INCLUDE_DIRS})
#LINK_DIRECTORIES(${Caffe_LIBRARY_DIRS})
SET(PROJECT_THIRD_LIBS ${PROJECT_THIRD_LIBS} ${Caffe_LIBRARIES})
