SET(CUR_LIB_NAME "caffe")
SET(CUR_LIB_PATH "${PROJECT_THIRD_PATH}/${CUR_LIB_NAME}")
SET(CUR_LIB_LIB_PATH "${CUR_LIB_PATH}/lib")
SET(CMAKE_PREFIX_PATH ${CUR_LIB_PATH})

FIND_PACKAGE(Caffe REQUIRED)

MESSAGE(HELLO ${Caffe_INCLUDE_DIRS})
MESSAGE(HELLO ${Caffe_LIBRARIES})
MESSAGE(HELLO ${CUR_LIB_LIB_PATH})
INCLUDE_DIRECTORIES(${Caffe_INCLUDE_DIRS})
LINK_DIRECTORIES(${CUR_LIB_LIB_PATH})
SET(PROJECT_THIRD_LIBS ${PROJECT_THIRD_LIBS} ${Caffe_LIBRARIES})
