SET(CUR_LIB_NAME "gflags")
#SET(CUR_LIB_PATH "${PROJECT_THIRD_PATH}/${CUR_LIB_NAME}")
#SET(CMAKE_PREFIX_PATH ${CUR_LIB_PATH})

#INCLUDE(${PROJECT_CMAKE_PATH}/FindGFlags.cmake)
FIND_PACKAGE(GFlags REQUIRED)

INCLUDE_DIRECTORIES(${GFLAGS_INCLUDE_DIRS})
LINK_DIRECTORIES(${GFLAGS_LIBRARYRARY_DIRS})
SET(PROJECT_THIRD_LIBS ${PROJECT_THIRD_LIBS} ${GFLAGS_LIBRARIES})
