SET(CUR_LIB_NAME "glog")
SET(CUR_LIB_PATH "${PROJECT_THIRD_PATH}/${CUR_LIB_NAME}")
SET(CMAKE_PREFIX_PATH ${CUR_LIB_PATH})

INCLUDE(${PROJECT_CMAKE_PATH}/FindGlog.cmake)
#FIND_PACKAGE(Glog REQUIRED)

INCLUDE_DIRECTORIES(${GLOG_INCLUDE_DIRS})
LINK_DIRECTORIES(${GLOG_LIBRARYRARY_DIRS})
SET(PROJECT_THIRD_LIBS ${PROJECT_THIRD_LIBS} ${GLOG_LIBRARIES})
