SET(CUR_LIB_NAME "gtest")
SET(CUR_LIB_PATH "${PROJECT_THIRD_PATH}/${CUR_LIB_NAME}")
#SET(CMAKE_PREFIX_PATH ${CUR_LIB_PATH})
SET(CUR_LIB_INCLUDE_PATH "${CUR_LIB_PATH}/include")
SET(CUR_LIB_LIB_PATH "${CUR_LIB_PATH}/lib")
SET(CUR_LIB_LIBRARIES gmock gmock_main gtest gtest_main)

#FIND_PACKAGE(Gtest REQUIRED)

INCLUDE_DIRECTORIES(${CUR_LIB_INCLUDE_PATH})
LINK_DIRECTORIES(${CUR_LIB_LIB_PATH})
SET(PROJECT_THIRD_LIBS ${PROJECT_THIRD_LIBS} ${CUR_LIB_LIBRARIES})
