SET(CUR_LIB_NAME "opencv")
SET(CUR_LIB_PATH "${PROJECT_THIRD_PATH}/${CUR_LIB_NAME}")
SET(CMAKE_PREFIX_PATH ${CUR_LIB_PATH})

FIND_PACKAGE(OpenCV REQUIRED)

MESSAGE(HELLO ${OpenCV_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(${OpenCV_INCLUDE_DIRS})
#LINK_DIRECTORIES(${OpenCV_LIBRARY_DIRS})
SET(PROJECT_THIRD_LIBS ${PROJECT_THIRD_LIBS} ${OpenCV_LIBS})
