SET(CUR_LIB_NAME "pcl")
SET(CUR_LIB_PATH "${PROJECT_THIRD_PATH}/${CUR_LIB_NAME}")
SET(CMAKE_PREFIX_PATH ${CUR_LIB_PATH})

FIND_PACKAGE(PCL 1.8 REQUIRED)

INCLUDE_DIRECTORIES(${PCL_INCLUDE_DIRS})
LINK_DIRECTORIES(${PCL_LIBRARY_DIRS})
SET(PROJECT_THIRD_LIBS ${PROJECT_THIRD_LIBS} ${PCL_LIBRARIES})
