SET(CUR_LIB_NAME "yamlcpp")
#SET(CUR_LIB_PATH "${PROJECT_THIRD_PATH}/${CUR_LIB_NAME}")
#SET(CMAKE_PREFIX_PATH ${CUR_LIB_PATH})

INCLUDE(${PROJECT_CMAKE_PATH}/FindYamlCpp.cmake)
#FIND_PACKAGE(GFlags REQUIRED)

INCLUDE_DIRECTORIES(${YAMLCPP_INCLUDE_DIR})
#LINK_DIRECTORIES(${GFLAGS_LIBRARYRARY_DIRS})
SET(PROJECT_THIRD_LIBS ${PROJECT_THIRD_LIBS} ${YAMLCPP_LIBRARY})
